import Color from 'color'

export const MINIMUM_PLAYBACK_RATE = 0.1 // Must be greater than 0
export const MAXIMUM_PLAYBACK_RATE = 5
export const MOVE_THROUGH_RATE = 5
export const MINIMUM_SKIP_TIME = 1
export const MAXIMUM_SKIP_TIME = 60

export const PLAYBACK_RATE_INCREMENT_VALUE = 0.1
export const CONTROLS_VISIBILITY_TIMEOUT = 5 * 1000

export const TRANSITION_DURATION_MS = 250
export const TRANSITION_DURATION = `${TRANSITION_DURATION_MS}ms`

export const BACKGROUND_COLOR_SATURATION = 75
export const BACKGROUND_COLOR_LIGHTNESS = 30
export const BACKGROUND_COLOR_TRANSITION_DURATION_MS = 100
export const BACKGROUND_COLOR_TRANSITION_INCREMENTS_PER_SECOND = 5
export const BACKGROUND_COLOR_TRANSITION_HUE_INCREMENT = (
  BACKGROUND_COLOR_TRANSITION_INCREMENTS_PER_SECOND / (
    1000 / BACKGROUND_COLOR_TRANSITION_DURATION_MS
  )
)

export const AUDIO_METADATA_BACKGROUND_COLOR_LIGHTNESS_MODIFIER = 20

export const CONTROL_HEIGHT = '2em'
export const CONTROL_ICON_OFFSET = '.05em'

export const CONTROLS_FOREGROUND_COLOR = Color('white')
export const CONTROLS_SECONDARY_FOREGROUND_COLOR = CONTROLS_FOREGROUND_COLOR.lightness(75)
export const CONTROLS_TINTED_FOREGROUND_COLOR = CONTROLS_FOREGROUND_COLOR.lightness(90)
export const CONTROLS_FADED_FOREGROUND_COLOR = CONTROLS_FOREGROUND_COLOR.lightness(50)
export const CONTROLS_BACKGROUND_COLOR = CONTROLS_FOREGROUND_COLOR.lightness(40)
export const CONTROLS_SECONDARY_BACKGROUND_COLOR = CONTROLS_FOREGROUND_COLOR.lightness(60)
